### ISSUE TITLE
Document deployment

### ISSUE THREAD

**Issue by Peder2911** [prio-data/views3#10]
Write documentation for how to deploy ViEWS 3.

**Comment by Peder2911** [comment]
Now that you have gotten a sense of how to deploy V3 to Vagrant on your own system, what do you think about collaborating on this document Jim?

**Comment by Peder2911** [comment]
Sorry, forgot to tag you: Ping @jimdale 
I keep adding to the deployment docs, see the wiki for this repository. Could you look it over and see if anything needs further elaboration?

**Comment by jimdale** [comment]
Sure, I will take a look - documentation should not be too hard to write as vagrant and docker are very similar (which can cause problems of its own..)

**Comment by Peder2911** [comment]
Haha, I'm sure.
Good! Happy that you're adopting this style of work as fast as if you'd worked with this stuff for years already! :+1:

**Comment by Peder2911** [comment]
@jimdale looking at the documentation present in this wiki, could you have a look and see if there's anything important missing, or if something needs more elaboration?

https://github.com/prio-data/views3/wiki

**Comment by Peder2911** [comment]
Closed after feedback from Jim
